### ISSUE TITLE
CSVの日付フォーマットが変わっても問題ないようにする対応

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19_shizuoka-opendata_csv2json#14]
JSONの日付フォーマットは「2020-01-29T08:00:00.000Z」こんな感じとする必要がある。
そうしないとグラフモジュールが受け入れてくれない。

CSVの日付フォーマットが「2020-01-29」だったのがある日急に「2020/1/29」こうなってしまっても、JSONの日付フォーマットが変わってしまわないようにする必要がある。

今のままだと「2020/1/29T08:00:00.000Z」こんな感じになってしまってグラフモジュールが受け入れてくれない。

**Comment by nsaito9628** [comment]
帰宅したら、昨晩の「Merge pull request #5 from nsaito9628/develop2」を以下の内容に差し替えて再度プルリクします

コストは下げる方法は思いつかなかったですが、バカ除けとして追記するならre.split()を使うべき、みたいですね

アップデートされるデータの由来を考えると、バカ除けは入れておいたほうが無難な気がするので提案です

--------------------------------------------------------------------------------------------

import re

listDate = ["2020/4/1", "2020/4/2", "2020/04-3", "2020-04-5", "2020:4;07",  "2020.4.8"]

for n in range(len(listDate)):
    Date = re.split('[:;.,-/]',  listDate[n])
    for i in (1,2): Date[i] = Date[i].zfill(2)
    day = Date[0]+"-"+Date[1]+"-"+ Date[2]
    print(day)

-----------------------------------------------------------------------------------------------
[結果]

2020-04-01
2020-04-02
2020-04-03
2020-04-05
2020-04-07
2020-04-08
