### ISSUE TITLE
検査陽性者の状況

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19_shizuoka-opendata_csv2json#2]
検査陽性者の状況
Data.main_summary
★データカタログまだ無い(準備中？)

CSV
★不明
多分、以下のような感じ？
No,全国地方公共団体コード,都道府県名,市区町村名,公表_年月日,曜日,検査実施人数,陽性患者数,入院中,軽症・中等症,重症,退院,死亡
1,221309,静岡県,浜松市,2020-03-28,土,100,1,1,1,0,0,0
2,221309,静岡県,浜松市,2020-04-01,水,200,2,2,2,0,0,0
3,221309,静岡県,浜松市,2020-04-03,金,249,3,3,3,0,0,0

JSON
    "main_summary": {
        "attr": "検査実施人数",
        "value": 249,
        "children": [
            {
                "attr": "陽性患者数",
                "value": 3,
                "children": [
                    {
                        "attr": "入院中",
                        "value": 3,
                        "children": [
                            {
                                "attr": "軽症・中等症",
                                "value": 3
                            },
                            {
                                "attr": "重症",
                                "value": 0
                            }
                        ]
                    },
                    {
                        "attr": "退院",
                        "value": 0
                    },
                    {
                        "attr": "死亡",
                        "value": 0
                    }
                ]
            }
        ]
    },

実装すべきコード
source/covid19_main_summary.py

**Comment by nsaito9628** [comment]
2020/04/06公開

検査陽性者の状況
221309_hamamatsu_covid19_main_summary.csv

csv
No, 全国地方公共団体コード, 都道府県名, 市区町村名, 公表_年月日, 曜日, 検査実施人数, 陽性患者数, 入院中, 軽症・中軽症, 重症, 退院, 死亡
61, 221309, 静岡県, 浜松市, 2020/3/29, 日, 7, 1, 1, 1
62, 221309, 静岡県, 浜松市, 2020/3/30, 月, 9			
63, 221309, 静岡県, 浜松市, 2020/3/31, 火, 22			
64, 221309, 静岡県, 浜松市, 2020/4/1, 水, 11, 1, 1, 1
65, 221309, 静岡県, 浜松市, 2020/4/2, 木, 23			
66, 221309, 静岡県, 浜松市, 2020/4/3, 金, 20, 1, 1, 1

API
a3122ca8-a30b-4f64-ab17-a6fe95d46fba

JSON
以下の構造でcovid19_main_summary.pyに実装

"main_summary"：{
"attr"： "検査実施人数"、
"value"：249、
"children"：[
{
"attr"： "陽性患者数"、
"value"：3、
"children"：[
{
"attr"： "入院中"、
"値"：3、
"子供"：[
{
"attr"： "軽症・中等症"、
"値"：3
}、
{
"attr"： "重症"、
"値"：0
}
]
}、
{
" attr "："退院 "、
" value "：0
}、
{
" attr "："死亡 "、
"値"：0
}
]
}
]
}、

**Comment by ww2or3ww** [comment]
#11
