### ISSUE TITLE
陽性患者数

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19_shizuoka-opendata_csv2json#3]
陽性患者数
Data.patients_summary
★データカタログまだ無い(準備中？)

CSV
★不明
多分、以下のような感じ？
No,全国地方公共団体コード,都道府県名,市区町村名,公表_年月日,曜日,陽性患者_人数
1,221309,静岡県,浜松市,2020-04-01,水,1
1,221309,静岡県,浜松市,2020-04-02,木,1
1,221309,静岡県,浜松市,2020-04-03,金,1

JSON
{
    "patients_summary": {
        "date": "2020\/04\/3 21:00",
        "data": [
            {
              "日付": "2020-04-01T08:00:00.000Z",
              "小計": 1
            },
            {
              "日付": "2020-04-02T08:00:00.000Z",
              "小計": 0
            },
            {
              "日付": "2020-04-03T08:00:00.000Z",
              "小計": 1
            }
        ]
    },   
}

実装すべきコード
source/covid19_patients_summary.py

**Comment by nsaito9628** [comment]
2020/04/06公開

陽性患者数
221309_hamamatsu_covid19_main_summary.csv

csv
No,全国地方公共団体コード,都道府県名,市区町村名,公表_年月日, 曜日,陽性患者人数
1, 221309, 静岡県, 浜松市, 2020/3/29, 日, 1
2, 221309, 静岡県, 浜松市, 2020/4/1,水,1
3, 221309, 静岡県, 浜松市, 2020/4/3, 金,1

API
92f9ebcd-a3f1-4d5d-899b-d69214294a45

JSONは以下の構造covid19_patients_summary.pyに実装
{
"patients_summary"：{
"日付"： "2020/04/3 21:00"、
"データ"：[
{
"日付"： "2020-04-01T08：00：00.000Z"、
" 小計"：1
}、
{
"日付"： "2020-04-02T08：00：00.000Z"、
" 小計" ：0
}、
{
"日付"： "2020-04-03T08：00：00.000Z"、
" 小計"：1
}
]
}、
}

**Comment by ww2or3ww** [comment]
#11
