### ISSUE TITLE
[CSV仕様][検査陽性者の状況] 退院者が軽症だったか重症だったか分からない

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19_shizuoka-opendata_csv2json#33]
![ink (9)](https://user-images.githubusercontent.com/6513552/79919966-478c5380-846a-11ea-9f4a-caab36bfb0ad.png)

「入院中」の状態は「軽症・中等症」と「重症」と2つあり、
「入院中」==「軽症・中等症」＋「重症」となっている。

いっぽう「退院」は入院中の状態をもっていないため、入院した場合、
「軽症・中等症」から引けばいいのか「重症」から引けばいいのか分からない。

案１．
退院した場合、退院の数とは別に「軽症・中等症」や「重症」にマイナスの値を設定する。
例：
軽症・中軽症, 重症, 退院
-3, -1, 4
※csv2jsonのプログラム改修は不要。

案２．
退院とは別に「退院_軽症・中等症」や「退院_重症」の列を追加する。
退院_軽症・中等症, 退院_重症, 退院
3, 1, 4
※csv2jsonのプログラム改修が必要。

**Comment by nsaito9628** [comment]
* Issu opendatelink＃33 ＃34のcommitで4/22現在csvからの読み込みでマイナスが出る不具合に対応

* 元のcsvが案2に対応したらcsv2jsonを再度改修予定

**Comment by ww2or3ww** [comment]
@nsaito9628 ありがとうございました。

#34 と https://github.com/code-for-hamamatsu/covid19_shizuoka-opendata_csv2json/commit/f3a21dd87b8d2810861c4a0ff3dba20301981b2e にてCloseとなります。

「陽性患者の状況」オープンデータカタログはもう不要になりましたので削除してもらいましょう。
