### ISSUE TITLE
例外処理:リトライ

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19_shizuoka-opendata_csv2json#9]
各CSV変換処理を呼び出す共通部分にリトライ処理を加える。
APIコールやCSV取得時の通信エラーへの備え。

source/lambda_function.py

**Comment by nsaito9628** [comment]
どうでしょうか、手抜きしすぎ?

<提案内容>　
retryパッケージよりretry関数をデコレータでcovid19の各関数先頭に配置

<実装対象ファイル>
covid19_contacts.py
covid19_inspection_persons.py
covid19_main_summary.py
covid19_patients_summary.py
covid19_patients.py

**Comment by ww2or3ww** [comment]
@nsaito9628 retryパッケージってものがあるんですね？よろしくおねがいします！
リトライ回数は3回、間隔は200ms程度でお願いします。

**Comment by ww2or3ww** [comment]
@nsaito9628 すいません、やっぱりリトライ対応はもう少し考えさせてください。
このretryパッケージって失敗した際に例外をthrowする必要があって、3回失敗したら文字列を返す、みたいなことが出来ないのではないかと予想しています。
もう少し考えて、Interfaceクラスみたいな概念でやりたいと思ってます。
